# Config for deploybot.app
# Docs https://docs.deploybot.psdn.io/config/
# Ordered list of Github Deployment environments
deployments:
- name: development
# Automatically trigger deploy on default branch passing
# on_push: true
- name: staging
- name: production
